# Generated by Django 5.0.6 on 2025-12-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('NOT PAID', 'Not Paid'), ('PAYMENT UNDER REVIEW', 'Payment Under Review'), ('PAID', 'Paid')], default='NOT PAID', max_length=30),
        ),
    ]
